name: Code Test

inputs:
  SONARQUBE_SCAN_TOKEN:
    required: true
    type: string
  SONAR_URL:
    required: true
    type: string
  CHECKMARX_USER:
    required: true
    type: string
  CHECKMARX_PASS:
    required: true
    type: string
  CHECKMARX_CLIENT_SECRET:
    required: true
    type: string

runs:
  using: 'composite'

  steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Launch npm script
        shell: bash
        run: |
          npm ci
          npm run lint
          npm run test:unit -- --coverage

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
    
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ inputs.SONARQUBE_SCAN_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.SONAR_URL }}
        with:
          projectBaseDir: src

      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3
        continue-on-error: true
        with:
          project: TDF-SEFA-FRONTEND
          team: /CxServer/SEFA
          checkmarx_url: https://checkmarx-p.it.az.tgscloud.net
          checkmarx_username: ${{ inputs.CHECKMARX_USER }}
          checkmarx_password: ${{ inputs.CHECKMARX_PASS }}
          checkmarx_client_secret: ${{ inputs.CHECKMARX_CLIENT_SECRET }}
          break_build: false
          scanners: sast
          incremental: false
          bug_tracker: none
          params: |
            --namespace=${{ github.repository_owner }} /
            --repo-name=${{ github.event.repository.name }} /
            --branch=${{ github.ref }} /
            --exclude_folders='.scannerwork, e2e, node_modules, projects, scripts, mocks, dist' /

      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          config: >-
            p/r2c-security-audit
            p/ci
            p/xss
            p/r2c-ci
            p/secrets
            p/typescript
            p/r2c-bug-scan
            p/owasp-top-ten
            p/command-injection
          auditOn: push
          generateSarif: "1"
