name: Deploy to environment

inputs:
  PACKAGE_NAME:
    description: "Name of upload artifact for deployment"
    required: true
    type: string
  DEPLOY_WORKING_FOLDER:
    required: true
    type: string
  STATIC_WEBAPP_API_KEY: 
    required: true
    type: string
  ENV:
    description: "The dedicated environment"
    required: true
    type: string
  ARM_CLIENT_ID:
    required: true
    type: string
  ARM_CLIENT_SECRET:
    required: true
    type: string
  ARM_TENANT_ID:
    required: true
    type: string
  ARM_SUBSCRIPTION_ID:
    required: true
    type: string

runs:
  using: 'composite'

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Azure
      shell: bash
      run: |
        az login --service-principal -u ${{ inputs.ARM_CLIENT_ID }} -p ${{ inputs.ARM_CLIENT_SECRET }} --tenant ${{ inputs.ARM_TENANT_ID }} --output none
        az account set --subscription ${{ inputs.ARM_SUBSCRIPTION_ID }}
    
    - name: Download a Build Artificat
      uses: actions/download-artifact@v2.1.0
      with:
        name: ${{ inputs.PACKAGE_NAME }}
        path: ${{ inputs.DEPLOY_WORKING_FOLDER }}

    - name: Static Web Apps Deploy ${{ inputs.ENV }}
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.STATIC_WEBAPP_API_KEY }}
        repo_token: ""
        action: "upload"
        app_location: dist/
        skip_app_build: true
