name: '🚀 Build and Push to ACR'
on:
  workflow_dispatch:
  push:
    branches:
      - feat/devops_front

jobs:
  login-azure:
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Azure
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }} --output none
          az account set --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          
  build:
    name: Build and Push to ACR
    runs-on: ubuntu-latest
    environment: integration
    needs: login-azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push to ACR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/frontend_end_web:${{ secrets.IMAGE_TAG }}
          file: Dockerfile
